import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Navbar from '@/components/Navbar/Navbar'
import Footer from '@/components/Footer/Footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout ({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <head>
        <meta charSet="utf-8" />
        <link rel="icon" href="/images/logo.png" />
        <link rel="manifest" href="/manifest.json" />
        <meta name="theme-color" content="#000000" />
        <title>TugTek</title>
        <meta
          name="description"
          content="TugTek yeni nesil elektronik çözüm."
        />
        <meta name="twitter:card" content="summary" />
        <meta name="twitter:site" content="@tugtek" />
        <meta name="twitter:creator" content="@tugtek" />
        <meta name="twitter:title" content="TugTek" />
        <meta
          name="twitter:description"
          content="TugTek yeni nesil elektronik çözüm."
        />
        <meta name="twitter:image" content="/images/logo.png" />
        <meta property="og:title" content="TugTek" />
        <meta
          property="og:description"
          content="TugTek yeni nesil elektronik çözüm."
        />
        <meta property="og:image" content="/images/logo.png" />
        <meta property="og:url" content="https://tugtek.com" />
        <meta property="og:site_name" content="TugTek" />
        <meta property="og:locale" content="en_US" />
        <meta property="og:type" content="website" />
        <link rel="apple-touch-icon" href="/images/logo.png" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
      </head>
      <body className='w-screen h-full '>
        <div >
          <Navbar />
        </div>
        <div className=''>{children}</div>
        <div className='mt-32'>
          <Footer />
        </div>
      </body>
    </html>
  )
}
