import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Navbar from '@/components/Navbar/Navbar'
import Footer from '@/components/Footer/Footer'
import { SpeedInsights } from '@vercel/speed-insights/next'
import { Analytics } from '@vercel/analytics/react'
import { Link as ScrollLink, animateScroll as scroll } from 'react-scroll';
import { GoogleAnalytics } from '@next/third-parties/google'



const inter = Inter({ subsets: ['latin'] })

// export const metadata: Metadata = {
//   title: {
//     default: 'TugTek',
//     template: '%s | TugTek'
//   } ,
//   description: 'Generated by TugTek'
// }

export default function RootLayout ({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <head>
     
      {/* <script type="text/javascript">
  (function (w: any, d: Document, s: string, l: string, i: string) {
    w[l] = w[l] || [];
    w[l].push({ 'gtm.start': new Date().getTime(), event: 'gtm.js' });
    var f = d.getElementsByTagName(s)[0],
      j = d.createElement(s), dl = l != 'dataLayer' ? '&l=' + l : '';
    j.async = true;
    j.src = 'https://www.googletagmanager.com/gtm.js?id=' + i + dl;
    f.parentNode.insertBefore(j, f);
  })(window, document, 'script', 'dataLayer', 'GTM-P4BSM87L');
</script> */}


        <meta charSet="utf-8" />
        <link rel="icon" href="logo.png" />
        <link rel="manifest" href="/manifest.json" />
        <meta name="theme-color" content="#000000" />
        <title>TugTek</title>
        <meta
          name="description"
          content="TugTek yeni nesil elektronik çözüm."
        />
        <meta name="twitter:card" content="summary" />
        <meta name="twitter:site" content="@tugtek" />
        <meta name="twitter:creator" content="@tugtek" />
        <meta name="twitter:title" content="TugTek" />
        <meta
          name="twitter:description"
          content="TugTek yeni nesil elektronik çözüm."
        />
        <meta name="twitter:image" content="logo.png" />
        <meta property="og:title" content="TugTek" />
        <meta
          property="og:description"
          content="TugTek yeni nesil elektronik çözüm."
        />
        <meta property="og:image" content="logo.png" />
        <meta property="og:url" content="https://tugtek.com" />
        <meta property="og:site_name" content="TugTek" />
        <meta property="og:locale" content="en_US" />
        <meta property="og:type" content="website" />
        <link rel="apple-touch-icon" href="logo.png" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
      </head>

      <body className='w-screen h-full bg-white dark:bg-white'>
      <noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-P4BSM87L"
height="0" width="0" className='hidden'></iframe></noscript>
        <div>
          <Navbar />
        </div>
        <div className=''>
          {children}
          <GoogleAnalytics gaId="GTM-P4BSM87L" />
          <SpeedInsights />
          <Analytics />
        </div>
        <div className='mt-32'>
          <Footer />
        </div>
      </body>
    </html>
  )
}
